### PR TITLE
Add Brush Pegan test

### PR DESCRIPTION
**Pull request by ShouvikGhosh2048**

### CODE REVIEW

**Comment by ShouvikGhosh2048** [comment]
@sourish-cmi 
I've added `BPTest`, but I haven't added any getters from HypothesisTests, like `pvalue`, so those won't work without importing HypothesisTests.

Do we need to add any getters? If so, which?

**Comment by sourish-cmi** [comment]
> @sourish-cmi I've added `BPTest`, but I haven't added any getters from HypothesisTests, like `pvalue`, so those won't work without importing HypothesisTests.
> 
> Do we need to add any getters? If so, which?

@ShouvikGhosh2048  I think if you add `pvalue` and `confint` would be good enough.

**Comment by sourish-cmi** [comment]
Add functional testing. 

```Julia
julia> pvalue(BP_tst) = 0.46203539153321815
```

**Comment by ShouvikGhosh2048** [comment]
@sourish-cmi I've added the getters.
Could you try using confint with the bptest?

**Comment by sourish-cmi** [comment]
> Could you try using confint with the bptest?

Okay I got the error with confint

Then I looked into source code of `HypothesisTests.jl` - [here](https://github.com/JuliaStats/HypothesisTests.jl/blob/master/src/HypothesisTests.jl): 

It looks like they have created a place holder for `confint` - but it is not implemented.

I will ask them but for now lets drop the idea of `confint`. Lets just implement the `pvalue`.

**Comment by sourish-cmi** [comment]
All looks good. Did you add a functional test. We will need one when we will do a release for version 0.1.1

**Comment by ShouvikGhosh2048** [comment]
@sourish-cmi 
The `residuals` function doesn't work for logistic regression models. Is this test only for Linear Regression models?

**Comment by sourish-cmi** [comment]
> @sourish-cmi The `residuals` function doesn't work for logistic regression models. Is this test only for Linear Regression models?

@ShouvikGhosh2048 - yes you are correct. This is only for the Linear Regression model. In my PhD thesis, I wrote a function about extracting residual for Logistic Regression and others. We can make them available. It is not very difficult. It is just a few lines of code. 

Anyway, for now, I think if we can add document and functional testing and we can close this PR

**Comment by ShouvikGhosh2048** [comment]
I've added the docs and tests.

**Review by sourish-cmi — APPROVED** [review]

**Pull request merged**
