### PR TITLE
Fix readme

### LINKED ISSUE #104: Documentation correction request
@ShouvikGhosh2048 can you please correct two bugs on the [front page](https://github.com/xKDR/CRRao.jl) and raise a PR.

**Describe the bug**

1) On the [landing page ](https://github.com/xKDR/CRRao.jl), the installation instruction is wrong. The correct instruction would be:
```Julia
using Pkg; Pkg.add("CRRao")
```

2) The first chunk of code `model.fit` is wrong. The correct code would be `coeftable(model)`.

### PR DESCRIPTION
**Pull request by ShouvikGhosh2048**
@sourish-cmi 
Closes #104.

### CODE REVIEW

**Review by sourish-cmi — APPROVED** [review]

**Comment by sourish-cmi** [comment]
@ShouvikGhosh2048 @ayushpatnaikgit this was the simplest PR - but checks are failing. What do you think we should do? I looked into the error and looks like it is problem on the server side. Please let me know what is your thought.

**Comment by sourish-cmi** [comment]
@ShouvikGhosh2048 @ayushpatnaikgit looks like Bayesian tests are failing. Can you please check if this is the same problem with Turing that we faced before the official realises !!

**Comment by ShouvikGhosh2048** [comment]
I checked the test logs - there has been a change in the version of `Bijectors` (used by `Turing`).
I think the change in the version caused the outputs to change.
The initial 2 test runs for this PR failed the issue discussed here - https://github.com/TuringLang/Turing.jl/pull/1946#issuecomment-1438221630.
The remaining 7 runs are consistent, so I think we just need to update the values we use in the tests.

**Comment by sourish-cmi** [comment]
> I checked the test logs - there has been a change in the version of `Bijectors` (used by `Turing`). I think the change in the version caused the outputs to change. The initial 2 test runs for this PR failed due to the issue discussed here - [TuringLang/Turing.jl#1946 (comment)](https://github.com/TuringLang/Turing.jl/pull/1946#issuecomment-1438221630). The remaining 7 runs are consistent, so we need to update the values we use in the tests.

@ShouvikGhosh2048 Thanks for figuring it out. I don't know if updating the values will fix the problem. If they revert to the old setup, it will break down again. I commented on the PR - stating that our package is breaking down because of the bug. Let's wait for a day or two. If we don't get any response from them, we will take a call.

**Comment by sourish-cmi** [comment]
@ShouvikGhosh2048 This is the response [here](https://github.com/TuringLang/Turing.jl/pull/1946#issuecomment-1446392574). Looks like they are suggesting the same as you said. Please change the test as you recommend. That will fix the problem. Please go ahead and change the test as you recommended.

**Review by sourish-cmi — APPROVED** [review]

**Pull request merged**
