### PR TITLE
Add VI for linear regression

### PR DESCRIPTION
**Pull request by ShouvikGhosh2048**

### CODE REVIEW

**Comment by ShouvikGhosh2048** [comment]
@sourish-cmi @Nandini-Jaiswal

I've added VI for linear regression.

- I split `BayesianRegression` into `BayesianRegressionMCMC` and `BayesianRegressionVI` structs.
- I pass a boolean `use_vi` to determine whether to use MCMC or VI.
- For VI, I store the distribution, and sample it during prediction. (This technically makes the prediction random each time, I could change it to sample during creation and store the sampled values instead dist, if you prefer that.)
- I made seperate structs for `BayesianRegressionMCMC` and `BayesianRegressionVI` to store the chain and dist respectively. However we could just convert both to a matrix of samples (we will sample the dist for VI) and just have a single `BayesianRegression` struct which stores the matrix of samples. We would lose the info about the chain and dist though, I'm not sure if its important.

**Comment by sourish-cmi** [comment]
@ShouvikGhosh2048  Can you please add tests and check why the doc test is failing? Do you want me to provide some test!

**Comment by ShouvikGhosh2048** [comment]
I've added tests for VI, those are passing. The doc test are failing since I haven't made the changes for VI, I'll make them once we decide on the API.

**Comment by sourish-cmi** [comment]
Okay - can we meet over Google Meet?

**Comment by ShouvikGhosh2048** [comment]
I've made the changes we discussed and updated the docs.

I ended up removing `use_vi` and instead I use a `BayesianAlgorithm` struct defined here:
https://github.com/xKDR/CRRao.jl/pull/154/files#diff-b989ddbe26d5a6bf4e0714d4bc169310463a8e8bbcadaf6d5903d5fe34f6fc02R395-R432

I went with this since the algorithms have different parameters (MCMC needs the number of iterations and the number of initial observations we discard, and VI needs the number of samples, number of VI iterations and number of samples per VI step).

So now we do:
`model = fit(@formula(MPG ~ HP + WT + Gear), mtcars, LinearRegression(), prior)` - MCMC
`model = fit(@formula(MPG ~ HP + WT + Gear), mtcars, LinearRegression(), prior, VI())` - VI

If the API is fine, this PR is ready to merge.

**Comment by ShouvikGhosh2048** [comment]
@sourish-cmi 

I've made updates to the API and pushed the changes to my PR. If you are fine with integrating VI, then you can take a look at PR and merge it if you're fine with it, and then me and @Nandini-Jaiswal can continue implementing VI for the rest of the regression types, while you take a look at Turings VI.

**Review by sourish-cmi — APPROVED** [review]
Looks fine

**Comment by sourish-cmi** [comment]
I am fine with it. Merging the PR.

**Pull request merged**
