### PR TITLE
horse shoe prior for logistic regression

### PR DESCRIPTION
**Pull request by sourish-cmi**
horse shoe prior for logistic regression

### CODE REVIEW

**Comment by ayushpatnaikgit** [comment]
@codetalker7 can you please check why this is failing? Can you test it locally?

**Comment by ayushpatnaikgit** [comment]
@sourish-cmi can you make a turing only test case for this? Perhaps this is a problem with Turing + Github.

**Comment by sourish-cmi** [comment]
@ayushpatnaikgit - not sure how to make the test. Perhaps best we meet over the Google meet and discuss it

**Comment by sourish-cmi** [comment]
I ran the following test, and it looks like Turing is doing fine:

First, I ran the frequentist PoissonRegression()

```
using CRRao
fit = @fitmodel((Num ~ Target + Coop + NCost),data,PoissonRegression())
```

The output is:

```
Model Class: Poisson Regression
Likelihood Mode: Poison
Link Function: Log
Computing Method: Optimization
─────────────────────────────────────────────────────────────────────────────────
                        Coef.  Std. Error      z  Pr(>|z|)   Lower 95%  Upper 95%
─────────────────────────────────────────────────────────────────────────────────
(Intercept)         -1.91392    0.261667   -7.31    <1e-12  -2.42678    -1.40106
Target               0.157769   0.0653822   2.41    0.0158   0.0296218   0.285915
Coop                 1.15127    0.0561861  20.49    <1e-92   1.04114     1.26139
NCost: major loss   -0.324051   0.230055   -1.41    0.1590  -0.774951    0.126848
NCost: modest loss   1.71973    0.100518   17.11    <1e-64   1.52272     1.91674
NCost: net gain      0.463907   0.16992     2.73    0.0063   0.13087     0.796944
─────────────────────────────────────────────────────────────────────────────────
```

If Turing runs well then all estimates will be ball-park similar.

```
using Turing, Random, RDatasets, StatsModels
Random.seed!(123)
data = dataset("Zelig", "sanction")
formula = @formula(Num ~ Target + Coop + NCost)
formula = apply_schema(formula, schema(formula, data));
y, X = modelcols(formula, data);
@model PoissonReg(X, y) = begin
    p = size(X, 2);
    n = size(X, 1);
    #priors
    #priors
    h = 1.0
    λ ~ InverseGamma(h, h)
    α ~ Uniform(-λ, λ)
    β ~ filldist(Uniform(-λ, λ), p)
  
    ## link
    z = α .+ X * β
    mu = exp.(z)
    
    #likelihood
    for i = 1:n
        y[i] ~ Poisson(mu[i])
    end
end
PoissonReg_model=PoissonReg(X,y);
chain = sample(PoissonReg_model, NUTS(), 10000)
summaries, quantiles = describe(chain)
```

The output is:

```
Summary Statistics
  parameters      mean        std   naive_se      mcse         ess      rhat   ⋯
      Symbol   Float64    Float64    Float64   Float64     Float64   Float64   ⋯

           λ   32.6049   197.5302     1.9753    3.4590   3202.9556    1.0004   ⋯
           α   -2.6785     0.4402     0.0044    0.0413     23.2117    1.3890   ⋯
        β[1]    0.2804     0.0885     0.0009    0.0068     32.5039    1.2301   ⋯
        β[2]    1.2688     0.0782     0.0008    0.0064     29.0146    1.2802   ⋯
        β[3]   -0.3878     0.2339     0.0023    0.0038   5273.9692    1.0026   ⋯
        β[4]    1.8222     0.1127     0.0011    0.0054     77.7796    1.0876   ⋯
        β[5]    0.7339     0.2133     0.0021    0.0147     39.1131    1.1869   ⋯
                                                                1 column omitted
```

Hence we can say that Turing is doing fine.

**Review by ayushpatnaikgit — APPROVED** [review]

**Pull request merged**
