### PR TITLE
Add keyword arguments to frequentist models

### PR DESCRIPTION
**Pull request by ShouvikGhosh2048**
This PR adds keyword arguments to the frequentist models. (To be able to use GLM keyword arguments.)

### CODE REVIEW

**Comment by ShouvikGhosh2048** [comment]
@ayushpatnaikgit @sourish-cmi 
I haven't added documentation/tests for the kwargs.
For documentation, should I link to the corresponding GLM function or directly list out all the kwargs mentioned in the GLM docs?

**Comment by sourish-cmi** [comment]
> @ayushpatnaikgit @sourish-cmi I haven't added documentation/tests for the kwargs. For documentation, should I link to the corresponding GLM function or directly list out all the kwargs mentioned in the GLM docs?

It is better to add documents/test in the PR. I think it is better to list out all the `kwargs` mentioned in the GLM doc. Also link it to the corresponding GLM function. Because later if a new `kwargs` added in GLM.jl, we have to add the list in CRRao as well. At least user will also have link to original GLM.jl

**Comment by ShouvikGhosh2048** [comment]
I've added a link to the corresponding functions and mentioned that we support the same keywords.

Do we need tests? There are quite a few keywords to test.

**Comment by sourish-cmi** [comment]
> I've added a link in the docs to the corresponding functions and mentioned that we support the same keywords. The GLM documentation has descriptions for the keywords.
> 
> Do we need tests? There are quite a few keywords to test.

I think two things to check. (1) If the current tests are all passing. I believe it is all passing. (2) Second, if tests for keywords are passing. Just check for a few keywords like `weights` - at this moment. That is a requirement from the survey package.

**Comment by ShouvikGhosh2048** [comment]
I've added tests for keywords (wts for Linear, Logistic and Poisson, atol for NegativeBinomial).

**Review by sourish-cmi — APPROVED** [review]

**Pull request merged**
