### PR TITLE
Change fitmodel macro to fit function

### PR DESCRIPTION
**Pull request by ShouvikGhosh2048**

### CODE REVIEW

**Comment by ayushpatnaikgit** [comment]
@ShouvikGhosh2048 can you check why the CI is failing on GitHub? It seems to be passing locally on my machine.

**Comment by ayushpatnaikgit** [comment]
@ShouvikGhosh2048 can you also find out how we should integrate with StatsAPI?

**Comment by ShouvikGhosh2048** [comment]
1) I think the Poisson Regression with uniform prior test is failing. The tests pass locally for me too. I'm not sure why they're failing.

2) [Extending StatsAPI](https://github.com/JuliaStats/StatsAPI.jl#extending-statsapijl-functions) - We'll have to take StatsAPI as a dependency, and then define their methods on our types.

**Comment by ayushpatnaikgit** [comment]
> 1. I think the Poisson Regression with uniform prior test is failing. The tests pass locally for me too. I'm not sure why they're failing.
> 
>     2. [Extending StatsAPI](https://github.com/JuliaStats/StatsAPI.jl#extending-statsapijl-functions) - We'll have to take StatsAPI as a dependency, and then define their methods on our types.

Can you do number 2?

**Comment by ayushpatnaikgit** [comment]
@sourish-cmi is Poisson with uniform prior supposed to be a problem?

**Comment by ayushpatnaikgit** [comment]
@sourish-cmi is Poisson with uniform prior supposed to be a problem?

**Comment by ShouvikGhosh2048** [comment]
> > 1. I think the Poisson Regression with uniform prior test is failing. The tests pass locally for me too. I'm not sure why they're failing.
> >    
> >    2. [Extending StatsAPI](https://github.com/JuliaStats/StatsAPI.jl#extending-statsapijl-functions) - We'll have to take StatsAPI as a dependency, and then define their methods on our types.
> 
> Can you do number 2?

Should I make a seperate PR?

**Comment by ayushpatnaikgit** [comment]
> 

Can you do it in the same PR?

**Comment by sourish-cmi** [comment]
@ShouvikGhosh2048 @ayushpatnaikgit it will be great if we can implement the [Extending StatsApi](https://github.com/JuliaStats/StatsAPI.jl#extending-statsapijl-functions)

Any idea how much time you would need to implement it?

I am working on the integration of the `GaussianProcesses.jl` into `CRRao.jl`.  Currently I am working on the design. Once this PR is complete - I will update my branch and then I will resume the code development for integration.

**Comment by sourish-cmi** [comment]
> @sourish-cmi is Poisson with uniform prior supposed to be a problem?

Theoretically yes. But the way I defined the `uniform prior` if someone choose `h` not too small - then MCMC would converege

**Comment by sourish-cmi** [comment]
A test should be:
```Julia
using CRRao, RDatasets, StatsPlots, Plots, StatsModels
mtcars = dataset("datasets", "mtcars")

model = fit(MPG ~ HP + log(WT) + Gear^2, mtcars)
```

**Review by sourish-cmi — APPROVED** [review]
All test passed. In the next PR we will change to fit for Horseshoe prior.

**Pull request merged**
